% GOAFEM_CONVERGENCEPLOT plots a variety of different convergence rates
% against reference rates. 
%
% Estimates for the errors in the primal (red) and dual (blue) problems 
% are plotted, as well as the combined rate (magenta), which provides an
% estimate for the error in the goal functional.
%
% TR; 20 July 2022

c1 = 1.10*10^(2/3)*max([error_iter_u, error_dir_iter_u, error_iter_z, error_dir_iter_z]);
c2 = 0.80*10^(2/3)*min([error_iter_u(1), error_dir_iter_u(1), error_iter_z(1), error_dir_iter_z(1)]);
c3 = 1.25*(dof(end))^(2/3)*max([error_iter(end), error_dir_iter(end)]);
c4 = 1.00*(dof(end))^(2/3)*min([error_iter, error_dir_iter]);
l1 = dof(1)^0.9;
l2 = dof(end)^1.1;
l3 = min([error_iter_u(end), error_dir_iter_u(end), error_iter_z(end), error_dir_iter_z(end)])/10;
l4 = max([error_iter_u, error_dir_iter_u, error_iter_z, error_dir_iter_z])*2;
l5 = min([error_iter(end), error_dir_iter(end)])/10;
l6 = max([error_iter, error_dir_iter])*2;
m1 = mean(abs(err_s_dir_iter_u(1:iter) ./ err_s_dir_iter_z(1:iter) - 1));
m2 = mean(abs(err_p_dir_iter_u(1:iter) ./ err_p_dir_iter_z(1:iter) - 1));

if min(m1,m2) <= 1e-1
    figure(3);
    loglog(dof, error_iter_u, '^-r', ...
           dof, error_dir_iter_u, 's-r', ...
           dof, error_iter_z, 'v--b', ...
           dof, error_dir_iter_z, 'd--b', ...
           dof, error_iter, 'o-m', ...
           dof, error_dir_iter, 's-m', ...
           [10^-1 10^8], c1*[10^-1 10^8].^(-1/3), 'k:', ...
           [10^-1 10^8], c2*[10^-1 10^8].^(-3/8), 'k-.', ...
           [10^-1 10^8], c3*[10^-1 10^8].^(-2/3), 'k--', ...
           [10^-1 10^8], c4*[10^-1 10^8].^(-3/4), 'k-')
    hold on
    grid on
    xlabel('degrees of freedom')
    ylabel('estimated error')
    legend('$\bar\eta_u$ (total)', '$\eta_u$ (total)', ...
           '$\bar\eta_z$ (total)', '$\eta_z$ (total)', ...
           '$\bar\eta$ (total)', '$\eta$ (total)', ...
           '$\mathcal{O}(N^{-1/3})$',...
           '$\mathcal{O}(N^{-3/8})$',...
           '$\mathcal{O}(N^{-2/3})$',...
           '$\mathcal{O}(N^{-3/4})$',...
           'Location', 'Best', 'interpreter', 'latex');
    axis ([l1 l2 l5 l4])

    figure(4);
    loglog(dof, error_dir_iter_u, 's-r', ...        
           dof, err_s_dir_iter_u, 'o-r', ...
           dof, err_p_dir_iter_u, '+-r', ...
           dof, error_dir_iter_z, 'd--b', ...
           dof, err_s_dir_iter_z, '*--b', ...
           dof, err_p_dir_iter_z, 'x--b', ...
           [10^-1 10^8], c1*[10^-1 10^8].^(-1/3), 'k:', ...
           [10^-1 10^8], c2*[10^-1 10^8].^(-3/8), 'k-.')
    hold on
    grid on
    xlabel('degrees of freedom')
    ylabel('estimated error')
    legend('$\eta_u$ (total)', '$\mu_u$ (spatial)', '$\tau_u$ (parametric)', ...
           '$\eta_z$ (total)', '$\mu_z$ (spatial)', '$\tau_z$ (parametric)', ...
           '$\mathcal{O}(N^{-1/3})$', ...
           '$\mathcal{O}(N^{-3/8})$', ...
           'Location', 'Best', 'interpreter', 'latex')
    axis ([l1 l2 l3 l4])

    figure(5);
    loglog(dof, error_iter_u, '^-r', ...
           dof, err_s_iter_u, 'o-r', ...
           dof, err_p_iter_u, '+-r', ...
           dof, error_iter_z, 'v--b', ...
           dof, err_s_iter_z, '*--b', ...
           dof, err_p_iter_z, 'x--b', ...
           [10^-1 10^8], c1*[10^-1 10^8].^(-1/3), 'k:', ...
           [10^-1 10^8], c2*[10^-1 10^8].^(-3/8), 'k-.')
    hold on
    grid on
    xlabel('degrees of freedom')
    ylabel('estimated error')
    legend('$\bar\eta_u$ (total)', '$\bar\mu_u$ (spatial)', '$\bar\tau_u$ (parametric)', ...
           '$\bar\eta_z$ (total)', '$\bar\mu_z$ (spatial)', '$\bar\tau_z$ (parametric)', ...
           '$\mathcal{O}(N^{-1/3})$', ...
           '$\mathcal{O}(N^{-3/8})$', ...
           'Location', 'Best', 'interpreter', 'latex');
    axis ([l1 l2 l3 l4])
else
    figure(3);
    loglog(dof, error_iter_u, '^-r', ...
           dof, error_dir_iter_u, 's-r', ...
           dof, error_iter_z, 'v-b', ...
           dof, error_dir_iter_z, 'd-b', ...
           dof, error_iter, 'o-m', ...
           dof, error_dir_iter, 's-m', ...
           [10^-1 10^8], c1*[10^-1 10^8].^(-1/3), 'k:', ...
           [10^-1 10^8], c2*[10^-1 10^8].^(-3/8), 'k-.', ...
           [10^-1 10^8], c3*[10^-1 10^8].^(-2/3), 'k--', ...
           [10^-1 10^8], c4*[10^-1 10^8].^(-3/4), 'k-')
    hold on
    grid on
    xlabel('degrees of freedom')
    ylabel('estimated error')
    legend('$\bar\eta_u$ (total)', '$\eta_u$ (total)', ...
           '$\bar\eta_z$ (total)', '$\eta_z$ (total)', ...
           '$\bar\eta$ (total)', '$\eta$ (total)', ...
           '$\mathcal{O}(N^{-1/3})$',...
           '$\mathcal{O}(N^{-3/8})$',...
           '$\mathcal{O}(N^{-2/3})$',...
           '$\mathcal{O}(N^{-3/4})$',...
           'Location', 'Best', 'interpreter', 'latex');
    axis ([l1 l2 l5 l4])

    figure(4);
    loglog(dof, error_dir_iter_u, 's-r', ...        
           dof, err_s_dir_iter_u, 'o-r', ...
           dof, err_p_dir_iter_u, '+-r', ...
           dof, error_dir_iter_z, 'd-b', ...
           dof, err_s_dir_iter_z, '*-b', ...
           dof, err_p_dir_iter_z, 'x-b', ...
           [10^-1 10^8], c1*[10^-1 10^8].^(-1/3), 'k:', ...
           [10^-1 10^8], c2*[10^-1 10^8].^(-3/8), 'k-.')
    hold on
    grid on
    xlabel('degrees of freedom')
    ylabel('estimated error')
    legend('$\eta_u$ (total)', '$\mu_u$ (spatial)', '$\tau_u$ (parametric)', ...
           '$\eta_z$ (total)', '$\mu_z$ (spatial)', '$\tau_z$ (parametric)', ...
           '$\mathcal{O}(N^{-1/3})$', ...
           '$\mathcal{O}(N^{-3/8})$', ...
           'Location', 'Best', 'interpreter', 'latex')
    axis ([l1 l2 l3 l4])

    figure(5);
    loglog(dof, error_iter_u, '^-r', ...
           dof, err_s_iter_u, 'o-r', ...
           dof, err_p_iter_u, '+-r', ...
           dof, error_iter_z, 'v-b', ...
           dof, err_s_iter_z, '*-b', ...
           dof, err_p_iter_z, 'x-b', ...
           [10^-1 10^8], c1*[10^-1 10^8].^(-1/3), 'k:', ...
           [10^-1 10^8], c2*[10^-1 10^8].^(-3/8), 'k-.')
    hold on
    grid on
    xlabel('degrees of freedom')
    ylabel('estimated error')
    legend('$\bar\eta_u$ (total)', '$\bar\mu_u$ (spatial)', '$\bar\tau_u$ (parametric)', ...
           '$\bar\eta_z$ (total)', '$\bar\mu_z$ (spatial)', '$\bar\tau_z$ (parametric)', ...
           '$\mathcal{O}(N^{-1/3})$', ...
           '$\mathcal{O}(N^{-3/8})$', ...
           'Location', 'Best', 'interpreter', 'latex');
    axis ([l1 l2 l3 l4])
end